export interface AgentPreset {
  id: string;
  name: string;
  role: string;
  department: string;
  kind: "llm" | "external" | "controller";
  autonomy: number;
  color: string;
  characterSpriteId: string;
  capabilities: string[];
  permissions: string[];
  tools: string[];
  requireApproval: boolean;
  systemPrompt: string;
}

export const AGENT_PRESETS: AgentPreset[] = [
  {
    id: "manager",
    name: "Manager",
    role: "Engineering Manager",
    department: "engineering",
    kind: "controller",
    autonomy: 3,
    color: "#5aa9e0",
    characterSpriteId: "modern-adam",
    capabilities: ["delegate_tasks", "approve_tasks", "code_analysis"],
    permissions: ["delegate_tasks", "approve_tasks", "repository.read"],
    tools: ["code_analysis", "repository_read"],
    requireApproval: false,
    systemPrompt:
      "You are a manager. Interpret the objective, plan, split the work, delegate formal commands to subordinates, review evidence before approving. Never execute work that belongs to a subordinate.",
  },
  {
    id: "developer",
    name: "Developer",
    role: "Developer",
    department: "engineering",
    kind: "llm",
    autonomy: 1,
    color: "#f2b544",
    characterSpriteId: "modern-alex",
    capabilities: ["repository_read", "repository_write", "testing", "code_analysis"],
    permissions: [
      "repository.read",
      "repository.write",
      "tests.execute",
      "git.branch.create",
      "git.commit",
    ],
    tools: ["repository_read", "repository_write", "testing"],
    requireApproval: false,
    systemPrompt:
      "You are a developer. Execute exactly the command received. Do not expand scope. Return evidence (diffs, test output).",
  },
  {
    id: "researcher",
    name: "Researcher",
    role: "Research Agent",
    department: "research",
    kind: "llm",
    autonomy: 2,
    color: "#a07ce0",
    characterSpriteId: "modern-amelia",
    capabilities: ["browse_web", "code_analysis"],
    permissions: ["web.browse", "repository.read"],
    tools: ["web_search", "browser", "repository_read"],
    requireApproval: false,
    systemPrompt:
      "You are a researcher. Investigate within the requested scope and return referenced findings.",
  },
  {
    id: "qa",
    name: "QA",
    role: "QA Engineer",
    department: "qa",
    kind: "llm",
    autonomy: 1,
    color: "#5ad1a6",
    characterSpriteId: "modern-bob",
    capabilities: ["testing", "repository_read"],
    permissions: ["repository.read", "tests.execute"],
    tools: ["testing", "repository_read"],
    requireApproval: false,
    systemPrompt:
      "You are QA. Verify deliverables by running tests. Report failures honestly. Never fake success.",
  },
  {
    id: "security",
    name: "Security",
    role: "Security Analyst",
    department: "security",
    kind: "llm",
    autonomy: 1,
    color: "#d95a5a",
    characterSpriteId: "modern-adam",
    capabilities: ["code_analysis", "repository_read"],
    permissions: ["repository.read"],
    tools: ["code_analysis", "repository_read"],
    requireApproval: true,
    systemPrompt:
      "You are a security analyst. Review for vulnerabilities and report risk levels with evidence.",
  },
  {
    id: "product",
    name: "Product",
    role: "Product Manager",
    department: "product",
    kind: "controller",
    autonomy: 3,
    color: "#e08c5a",
    characterSpriteId: "modern-amelia",
    capabilities: ["delegate_tasks", "approve_tasks"],
    permissions: ["delegate_tasks", "approve_tasks"],
    tools: [],
    requireApproval: false,
    systemPrompt:
      "You are a product manager. Translate goals into scoped tasks and acceptance criteria.",
  },
  {
    id: "designer",
    name: "Designer",
    role: "UX Designer",
    department: "design",
    kind: "llm",
    autonomy: 1,
    color: "#e07ca8",
    characterSpriteId: "modern-amelia",
    capabilities: ["browser"],
    permissions: ["repository.read", "web.browse"],
    tools: ["browser"],
    requireApproval: false,
    systemPrompt:
      "You are a UX designer. Produce specs and rationale for the requested scope only.",
  },
  {
    id: "documentation",
    name: "Documentation",
    role: "Documentation Agent",
    department: "engineering",
    kind: "llm",
    autonomy: 1,
    color: "#c8d15a",
    characterSpriteId: "modern-bob",
    capabilities: ["repository_read", "repository_write"],
    permissions: ["repository.read", "repository.write"],
    tools: ["repository_read", "repository_write"],
    requireApproval: false,
    systemPrompt: "You write documentation for the exact scope delegated. Reference sources.",
  },
  {
    id: "devops",
    name: "DevOps",
    role: "DevOps Engineer",
    department: "operations",
    kind: "llm",
    autonomy: 1,
    color: "#8a9bb0",
    characterSpriteId: "modern-adam",
    capabilities: ["shell", "github"],
    permissions: ["repository.read", "shell.execute", "deploy.staging", "github.pr.create"],
    tools: ["shell", "github_pr_create", "deploy_staging"],
    requireApproval: true,
    systemPrompt: "You are DevOps. Production actions always require human approval.",
  },
  {
    id: "external",
    name: "External Agent (Claudinho)",
    role: "Developer",
    department: "engineering",
    kind: "external",
    autonomy: 1,
    color: "#f2b544",
    characterSpriteId: "modern-alex",
    capabilities: [
      "repository_read",
      "repository_write",
      "shell",
      "github",
      "testing",
      "browser",
      "filesystem",
      "code_analysis",
    ],
    permissions: [
      "repository.read",
      "repository.write",
      "tests.execute",
      "git.branch.create",
      "git.commit",
    ],
    tools: ["repository_read", "repository_write", "shell", "testing", "git_commit"],
    requireApproval: true,
    systemPrompt:
      "You are an external executor. Run exactly what the controller orders. Return evidence. Never expand scope.",
  },
  {
    id: "custom",
    name: "Custom",
    role: "Agent",
    department: "engineering",
    kind: "llm",
    autonomy: 1,
    color: "#7c8aa5",
    characterSpriteId: "modern-bob",
    capabilities: [],
    permissions: [],
    tools: [],
    requireApproval: false,
    systemPrompt: "",
  },
];
